//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary.Manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalLibraryDBEntities : DbContext
    {
        public DigitalLibraryDBEntities()
            : base("name=DigitalLibraryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BooksTable> BooksTables { get; set; }
        public virtual DbSet<CatagoryTable> CatagoryTables { get; set; }
        public virtual DbSet<loginTable> loginTables { get; set; }
    }
}
